# Generated by Django 6.0.6 on 2026-06-22 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public-facing UUID.', unique=True)),
                ('mattermost_user_id', models.CharField(db_index=True, help_text='Mattermost user ID of the bookmark creator.', max_length=64)),
                ('url', models.URLField(help_text='Original bookmarked URL.', max_length=2048, unique=True)),
                ('domain', models.CharField(db_index=True, help_text='Extracted domain (e.g. github.com).', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', help_text='Remote preview image URL (OG/Twitter).', max_length=2048)),
                ('favicon_url', models.URLField(blank=True, default='', help_text='Remote favicon URL.', max_length=2048)),
                ('bookmark_type', models.CharField(choices=[('website', 'Website'), ('article', 'Article'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('reddit', 'Reddit'), ('pdf', 'PDF'), ('documentation', 'Documentation'), ('other', 'Other')], db_index=True, default='website', max_length=30)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider-specific metadata (stars, forks, channel, etc.).')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='#6366f1', help_text='Hex color code (e.g. #6366f1).', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookmarkAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('og_image', 'OpenGraph Image'), ('favicon', 'Favicon'), ('youtube_thumbnail', 'YouTube Thumbnail'), ('pdf_cover', 'PDF Cover')], max_length=30)),
                ('original_url', models.URLField(max_length=2048)),
                ('file', models.ImageField(upload_to='bookmarks/assets/')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='bookmarks.bookmark')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddField(
            model_name='bookmark',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='bookmarks.collection'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='bookmarks.tag'),
        ),
    ]
