version: "3.8"

services:
  reminderbot:
    build: .
    container_name: reminderbot
    restart: unless-stopped
    ports:
      - "8999:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=reminderbot.settings
