# Generated by Django 6.0.6 on 2026-06-19 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public-facing UUID for API and Mattermost interactions.', unique=True)),
                ('mattermost_user_id', models.CharField(blank=True, db_index=True, default='', help_text='Mattermost user ID of the reminder creator.', max_length=64)),
                ('title', models.CharField(help_text='Short title for the reminder.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional longer description.')),
                ('reminder_date', models.DateField(blank=True, help_text='Date portion of the reminder (for display / filtering).', null=True)),
                ('reminder_datetime', models.DateTimeField(db_index=True, help_text='Full date-time when the reminder should fire.')),
                ('repeat_type', models.CharField(choices=[('none', 'Never'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', help_text='Recurrence pattern for the reminder.', max_length=10)),
                ('snooze_minutes', models.PositiveIntegerField(default=0, help_text='Minutes to snooze when triggered (0 = no snooze).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current lifecycle status.', max_length=10)),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent trigger.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the reminder was marked completed.', null=True)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['reminder_datetime'],
            },
        ),
    ]
