# Generated by Django 6.0.6 on 2026-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='monthly_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1–31) for day_of_month mode.', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='monthly_mode',
            field=models.CharField(blank=True, choices=[('day_of_month', 'Day Of Month'), ('weekday_position', 'Weekday Position')], default='', help_text='Whether to anchor monthly recurrence to a day number or weekday position.', max_length=30),
        ),
        migrations.AddField(
            model_name='reminder',
            name='monthly_week',
            field=models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('last', 'Last')], default='', help_text='Which week-of-month for weekday_position mode.', max_length=10),
        ),
        migrations.AddField(
            model_name='reminder',
            name='monthly_weekday',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='', help_text='Which weekday for weekday_position mode.', max_length=10),
        ),
        migrations.AddField(
            model_name='reminder',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this reminder has been triggered so far.'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_end_after',
            field=models.PositiveIntegerField(blank=True, help_text='Stop recurrence after this many occurrences.', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_end_date',
            field=models.DateField(blank=True, help_text='Stop recurrence after this date.', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_forever',
            field=models.BooleanField(default=True, help_text='If True, the recurrence never ends.'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_interval',
            field=models.PositiveIntegerField(default=1, help_text='How many units between recurrences (e.g. 2 = every 2 …).'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_unit',
            field=models.CharField(blank=True, choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='', help_text='Unit for interval recurrence (minute, hour, day, …).', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='List of weekday names, e.g. ["monday","friday"].'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_datetime',
            field=models.DateTimeField(db_index=True, help_text='Full date-time when the reminder should fire next.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'One Time'), ('interval', 'Interval'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', help_text='Top-level recurrence category.', max_length=10),
        ),
    ]
