# Generated by Django 6.0.6 on 2026-06-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_monthly_day_reminder_monthly_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='snooze_minutes',
        ),
        migrations.AddField(
            model_name='reminder',
            name='yearly_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day number (1-31) for yearly repeat.', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='yearly_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month number (1-12) for yearly repeat.', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='monthly_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month for monthly repeat.', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='monthly_mode',
            field=models.CharField(blank=True, default='', help_text='Monthly recurrence mode: day_of_month or weekday_position.', max_length=30),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='monthly_week',
            field=models.CharField(blank=True, default='', help_text='Week position for monthly repeat: first, second, third, fourth, last.', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='monthly_weekday',
            field=models.CharField(blank=True, default='', help_text='Weekday for monthly repeat: monday, ..., sunday.', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of how many times this reminder has triggered.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_datetime',
            field=models.DateTimeField(db_index=True, help_text='Full date-time when the reminder should fire.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeat_end_after',
            field=models.PositiveIntegerField(blank=True, help_text='End recurrence after N occurrences.', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeat_end_date',
            field=models.DateField(blank=True, help_text='End date for the recurrence.', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeat_forever',
            field=models.BooleanField(default=True, help_text='Whether the recurrence repeats indefinitely.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeat_interval',
            field=models.PositiveIntegerField(default=1, help_text='Interval value for repetition.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'One Time'), ('interval', 'Interval'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', help_text='Recurrence pattern for the reminder.', max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeat_unit',
            field=models.CharField(blank=True, choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='', help_text='Unit for repetition interval.', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='repeat_weekdays',
            field=models.JSONField(blank=True, default=list, help_text="List of weekdays for weekly repeat (e.g. ['monday', 'friday'])."),
        ),
    ]
