# Generated by Django 6.0.6 on 2026-06-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_remove_reminder_reminder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Next scheduled execution time.', null=True),
        ),
    ]
